
[General]
	#Print all found mob IDS to the console, will cause spam
	printIDs = false
	#Protects all mobs from fire
	protectAllMobs = false
	#Protects these mods from fire (any mobs with these namespaces)
	mods = ["iceandfire", "minecraft", "monsterplus", "mutantmonsters"]
	#Protects these mobs from fire (any mobs with these ids (namespace:name))
	mobs = ["minecraft:husk", "minecraft:zombie_villager", "minecraft:phantom", "minecraft:skeleton", "minecraft:stray"]

