// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<harvestcraft:freshwateritem> * 8, [<harvestcraft:freshwateritem>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<immersiveengineering:material:1> * 4, [[<minecraft:iron_ingot>], [<minecraft:iron_ingot>]]);
recipes.removeShaped(<nuclearcraft:boots_hazmat>, [[<nuclearcraft:rad_shielding:2>, <ore:dyeBlack>, <nuclearcraft:rad_shielding:2>], [<nuclearcraft:part:6>, <minecraft:leather_boots>, <nuclearcraft:part:6>]]);
recipes.removeShaped(<nuclearcraft:legs_hazmat>, [[<minecraft:dye:11>, <nuclearcraft:part:6>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding:2>, <minecraft:leather_leggings>, <nuclearcraft:rad_shielding:2>], [<minecraft:wool>, null, <minecraft:wool>]]);
recipes.removeShaped(<nuclearcraft:chest_hazmat>, [[<minecraft:wool>, <nuclearcraft:rad_shielding:2>, <minecraft:wool>], [<ore:dyeYellow>, <minecraft:leather_chestplate>, <ore:dyeYellow>], [<nuclearcraft:rad_shielding:2>, <minecraft:wool>, <nuclearcraft:rad_shielding:2>]]);
recipes.removeShaped(<nuclearcraft:helm_hazmat>, [[<ore:dyeYellow>, <ore:blockWoolWhite>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding:2>, <minecraft:leather_helmet>, <nuclearcraft:rad_shielding:2>], [<ore:bioplastic>, <ore:ingotSteel>, <ore:bioplastic>]]);
recipes.removeShaped(<openmodularturrets:ammo_meta:1> * 64, [[null, <ore:ingotIron>], [<minecraft:gunpowder>, <minecraft:redstone>], [null, <ore:ingotIron>]]);
recipes.removeShaped(<openmodularturrets:ammo_meta:4> * 32, [[null, <minecraft:iron_ingot>, null], [<minecraft:iron_ingot>, <minecraft:tnt>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:redstone>, <minecraft:iron_ingot>]]);
recipes.removeShaped(<openmodularturrets:ammo_meta:3> * 32, [[null, <ore:dustRedstone>, null], [<ore:ingotIron>, <ore:gunpowder>, <ore:ingotIron>], [null, <ore:ingotIron>, null]]);
recipes.removeShaped(<openmodularturrets:ammo_meta:1> * 64, [[null, <minecraft:iron_ingot>], [<minecraft:gunpowder>, <minecraft:redstone>], [null, <minecraft:iron_ingot>]]);


// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<minecraft:dye>, [<ore:listAllwater>, <ore:charcoal>]);
recipes.addShapeless(<minecraft:planks:1> * 4, [<ore:logWood>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<immersiveengineering:material:1> * 6, [[null, null, <ore:ingotIron>], [null, <minecraft:iron_ingot>, null], [<ore:ingotIron>, null, null]]);
recipes.addShaped(<nuclearcraft:boots_hazmat>, [[<minecraft:dye:11>, <minecraft:dye:11>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding>, <minecraft:leather_boots>, <nuclearcraft:rad_shielding>], [<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>]]);
recipes.addShaped(<nuclearcraft:legs_hazmat>, [[<minecraft:dye:11>, <minecraft:dye:11>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding>, <minecraft:leather_leggings>, <nuclearcraft:rad_shielding>], [<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>]]);
recipes.addShaped(<nuclearcraft:chest_hazmat>, [[<minecraft:dye:11>, <minecraft:dye:11>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding>, <minecraft:leather_chestplate>, <nuclearcraft:rad_shielding>], [<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>]]);
recipes.addShaped(<nuclearcraft:helm_hazmat>, [[<minecraft:dye:11>, <minecraft:dye:11>, <minecraft:dye:11>], [<nuclearcraft:rad_shielding>, <minecraft:leather_helmet>, <nuclearcraft:rad_shielding>], [<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>]]);
recipes.addShaped(<appliedenergistics2:material:13>, [[<ore:itemSilicon>,  <ore:itemSilicon>, <ore:itemSilicon>], [<ore:itemSilicon>, <ore:ingotIron>, <ore:itemSilicon>], [<ore:itemSilicon>,  <ore:itemSilicon>, <ore:itemSilicon>]]);
recipes.addShaped(<appliedenergistics2:material:14>, [[<ore:itemSilicon>, <ore:itemSilicon>, <ore:itemSilicon>], [<ore:itemSilicon>, <ore:gemDiamond>, <ore:itemSilicon>], [<ore:itemSilicon>, <ore:itemSilicon>, <ore:itemSilicon>]]);
recipes.addShaped(<appliedenergistics2:material:15>, [[<ore:itemSilicon>, <ore:itemSilicon>, <ore:itemSilicon>], [ <ore:itemSilicon>, <ore:ingotGold>, <ore:itemSilicon>], [ <ore:itemSilicon>, <ore:itemSilicon>, <ore:itemSilicon>]]);
recipes.addShaped(<appliedenergistics2:material:19>, [[<ore:itemSilicon>,  <ore:itemSilicon>,  <ore:itemSilicon>], [<ore:itemSilicon>, null,  <ore:itemSilicon>], [<ore:itemSilicon>, <ore:itemSilicon>, <ore:itemSilicon>]]);
recipes.addShaped(<openmodularturrets:ammo_meta:4> * 4, [[<ore:ingotIron>, <minecraft:tnt>, <ore:ingotIron>], [<ore:ingotIron>, <minecraft:gunpowder>, <ore:ingotIron>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>]]);
recipes.addShaped(<openmodularturrets:ammo_meta:3> * 16, [[<ore:ingotIron>, <minecraft:gunpowder>, <ore:ingotIron>], [<minecraft:gunpowder>, <minecraft:redstone>, <minecraft:gunpowder>], [<minecraft:iron_ingot>, <minecraft:gunpowder>, <minecraft:iron_ingot>]]);
recipes.addShaped(<openmodularturrets:ammo_meta:1> * 32, [[<ore:ingotIron>, <minecraft:gunpowder>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:redstone>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:redstone>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:sand> * 8, [[<biomesoplenty:dried_sand>, <biomesoplenty:dried_sand>, <biomesoplenty:dried_sand>], [<biomesoplenty:dried_sand>, <minecraft:water_bucket>, <biomesoplenty:dried_sand>], [<biomesoplenty:dried_sand>, <biomesoplenty:dried_sand>, <biomesoplenty:dried_sand>]]);
recipes.addShaped(<harvestcraft:freshwateritem>, [[<harvestcraft:freshwateritem>]]);

